import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export function Header(){

  return (

    <div className='sticky top-0'>
         <div className=" w-full absolute top-0 left-0 flex justify-between">

            <h1 className="text-3xl font-bold">dijfniudhgiundfiu</h1>

            <ul className="flex space-x-4 p-1 ">
            <li className='p-2  text-[white] hover:bg-tahiti'><Link href='/'>Home</Link></li>
              <li className='p-2  text-[white] hover:bg-tahiti'><Link href='/gallery'>Gallery</Link></li>
              <li className='p-2  text-[white] hover:bg-tahiti'>Work</li>
              <li className='p-2  text-[white] hover:bg-tahiti'>Contact</li>
            </ul>

          </div>
    </div>

   

  )


}


export default function Home() {
  return (
    <>
      <Head>
        <title className='text-3xl font-bold underline'>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className = "bg-[url('https://images.pexels.com/photos/15015528/pexels-photo-15015528.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')] w-full h-full absolute bg-cover">
          
          <div className='w-full h-full absolute top-0 left-0 flex justify-center items-center  '>

            <div >

              <h1 className="font-extrabold text-2xl  ">Captur Photography</h1>
              <h2>I capture movements in nature and keep them alive</h2>
              <button className='border-2'>Book Now</button>

            </div>
          </div>



          <Header />


          <div className='h-200'></div>


          
          
          

        </div>




      </main>
    </>
  )
}
